excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://Rakesh234.github.io
title: Laptop Repairing Course in Delhi | Institute
tagline: Repairing and Training 
description: Describe repairing tricks and education in laptop hardware and software training. 
paginate: 5